# type: ignore
# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/quorum.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fpb/quorum.proto\x12\tquorum.pb"A\n\x06Object\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\x12\x0c\n\x04name\x18\x08 \x01(\t"\x88\x02\n\x03Trx\x12\r\n\x05TrxId\x18\x01 \x01(\t\x12 \n\x04Type\x18\x02 \x01(\x0e\x32\x12.quorum.pb.TrxType\x12\x0f\n\x07GroupId\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x04 \x01(\x0c\x12\x11\n\tTimeStamp\x18\x05 \x01(\x03\x12\x0f\n\x07Version\x18\x06 \x01(\t\x12\x0f\n\x07\x45xpired\x18\x07 \x01(\x03\x12\x13\n\x0bResendCount\x18\x08 \x01(\x03\x12\r\n\x05Nonce\x18\t \x01(\x03\x12\x14\n\x0cSenderPubkey\x18\n \x01(\t\x12\x12\n\nSenderSign\x18\x0b \x01(\x0c\x12.\n\x0bStorageType\x18\x0c \x01(\x0e\x32\x19.quorum.pb.TrxStroageType"\xbe\x01\n\x05\x42lock\x12\x0f\n\x07\x42lockId\x18\x01 \x01(\t\x12\x0f\n\x07GroupId\x18\x02 \x01(\t\x12\x13\n\x0bPrevBlockId\x18\x03 \x01(\t\x12\x14\n\x0cPreviousHash\x18\x04 \x01(\x0c\x12\x1c\n\x04Trxs\x18\x05 \x03(\x0b\x32\x0e.quorum.pb.Trx\x12\x16\n\x0eProducerPubKey\x18\x06 \x01(\t\x12\x0c\n\x04Hash\x18\x07 \x01(\x0c\x12\x11\n\tSignature\x18\x08 \x01(\x0c\x12\x11\n\tTimeStamp\x18\t \x01(\x03*\xf5\x01\n\x07TrxType\x12\x08\n\x04POST\x10\x00\x12\n\n\x06SCHEMA\x10\x02\x12\x0c\n\x08PRODUCER\x10\x03\x12\x0c\n\x08\x41NNOUNCE\x10\x04\x12\x15\n\x11REQ_BLOCK_FORWARD\x10\x05\x12\x16\n\x12REQ_BLOCK_BACKWARD\x10\x06\x12\x12\n\x0eREQ_BLOCK_RESP\x10\x07\x12\x10\n\x0c\x42LOCK_SYNCED\x10\x08\x12\x12\n\x0e\x42LOCK_PRODUCED\x10\t\x12\x08\n\x04USER\x10\n\x12\x0e\n\nASK_PEERID\x10\x0b\x12\x13\n\x0f\x41SK_PEERID_RESP\x10\x0c\x12\x10\n\x0c\x43HAIN_CONFIG\x10\r\x12\x0e\n\nAPP_CONFIG\x10\x0e*&\n\x0eTrxStroageType\x12\t\n\x05\x43HAIN\x10\x00\x12\t\n\x05\x43\x41\x43HE\x10\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pb.quorum_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _TRXTYPE._serialized_start = 558
    _TRXTYPE._serialized_end = 803
    _TRXSTROAGETYPE._serialized_start = 805
    _TRXSTROAGETYPE._serialized_end = 843
    _OBJECT._serialized_start = 30
    _OBJECT._serialized_end = 95
    _TRX._serialized_start = 98
    _TRX._serialized_end = 362
    _BLOCK._serialized_start = 365
    _BLOCK._serialized_end = 555
# @@protoc_insertion_point(module_scope)
